
# This file is automatically generated, you probably don't want to edit this

chisqgofitOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "chisqgofitOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            calculate = "selectpower",
            typeinput = "stdeff",
            w = 0.13,
            df = 1,
            nrow = 2,
            ncol = 2,
            power = 0.8,
            alpha = 0.05,
            n = 200, ...) {

            super$initialize(
                package="jpwrss",
                name="chisqgofit",
                requiresData=FALSE,
                ...)

            private$..calculate <- jmvcore::OptionList$new(
                "calculate",
                calculate,
                options=list(
                    "selectpower",
                    "selectsamplesize"),
                default="selectpower")
            private$..typeinput <- jmvcore::OptionList$new(
                "typeinput",
                typeinput,
                options=list(
                    "cellprob",
                    "stdeff"),
                default="stdeff")
            private$..w <- jmvcore::OptionNumber$new(
                "w",
                w,
                default=0.13)
            private$..df <- jmvcore::OptionInteger$new(
                "df",
                df,
                default=1)
            private$..nrow <- jmvcore::OptionNumber$new(
                "nrow",
                nrow,
                default=2)
            private$..ncol <- jmvcore::OptionNumber$new(
                "ncol",
                ncol,
                default=2)
            private$..power <- jmvcore::OptionNumber$new(
                "power",
                power,
                default=0.8)
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                default=0.05)
            private$..n <- jmvcore::OptionNumber$new(
                "n",
                n,
                default=200)

            self$.addOption(private$..calculate)
            self$.addOption(private$..typeinput)
            self$.addOption(private$..w)
            self$.addOption(private$..df)
            self$.addOption(private$..nrow)
            self$.addOption(private$..ncol)
            self$.addOption(private$..power)
            self$.addOption(private$..alpha)
            self$.addOption(private$..n)
        }),
    active = list(
        calculate = function() private$..calculate$value,
        typeinput = function() private$..typeinput$value,
        w = function() private$..w$value,
        df = function() private$..df$value,
        nrow = function() private$..nrow$value,
        ncol = function() private$..ncol$value,
        power = function() private$..power$value,
        alpha = function() private$..alpha$value,
        n = function() private$..n$value),
    private = list(
        ..calculate = NA,
        ..typeinput = NA,
        ..w = NA,
        ..df = NA,
        ..nrow = NA,
        ..ncol = NA,
        ..power = NA,
        ..alpha = NA,
        ..n = NA)
)

chisqgofitResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "chisqgofitResults",
    inherit = jmvcore::Group,
    active = list(
        text2 = function() private$.items[["text2"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Goodness-of-Fit or Independence (Chi-square Test)",
                refs=list(
                    "pwrss"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text2",
                title="Goodness-of-Fit or Independence (Chi-square Test)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Goodness-of-Fit or Independence (Chi-square Test)",
                renderFun=".plot"))}))

chisqgofitBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "chisqgofitBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jpwrss",
                name = "chisqgofit",
                version = c(1,0,0),
                options = options,
                results = chisqgofitResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Goodness-of-Fit or Independence (Chi-square Test)
#'
#' 
#' @param calculate .
#' @param typeinput .
#' @param w .
#' @param df .
#' @param nrow .
#' @param ncol .
#' @param power .
#' @param alpha .
#' @param n .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text2} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
chisqgofit <- function(
    calculate = "selectpower",
    typeinput = "stdeff",
    w = 0.13,
    df = 1,
    nrow = 2,
    ncol = 2,
    power = 0.8,
    alpha = 0.05,
    n = 200) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("chisqgofit requires jmvcore to be installed (restart may be required)")


    options <- chisqgofitOptions$new(
        calculate = calculate,
        typeinput = typeinput,
        w = w,
        df = df,
        nrow = nrow,
        ncol = ncol,
        power = power,
        alpha = alpha,
        n = n)

    analysis <- chisqgofitClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

