
# This file is automatically generated, you probably don't want to edit this

ftestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ftestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            calculate = "selectpower",
            ncp = 1.96,
            df1 = 2,
            df2 = 199,
            alpha = 0.05, ...) {

            super$initialize(
                package="jpwrss",
                name="ftest",
                requiresData=FALSE,
                ...)

            private$..calculate <- jmvcore::OptionList$new(
                "calculate",
                calculate,
                options=list(
                    "selectpower"),
                default="selectpower")
            private$..ncp <- jmvcore::OptionNumber$new(
                "ncp",
                ncp,
                default=1.96)
            private$..df1 <- jmvcore::OptionInteger$new(
                "df1",
                df1,
                default=2)
            private$..df2 <- jmvcore::OptionInteger$new(
                "df2",
                df2,
                default=199)
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                default=0.05)

            self$.addOption(private$..calculate)
            self$.addOption(private$..ncp)
            self$.addOption(private$..df1)
            self$.addOption(private$..df2)
            self$.addOption(private$..alpha)
        }),
    active = list(
        calculate = function() private$..calculate$value,
        ncp = function() private$..ncp$value,
        df1 = function() private$..df1$value,
        df2 = function() private$..df2$value,
        alpha = function() private$..alpha$value),
    private = list(
        ..calculate = NA,
        ..ncp = NA,
        ..df1 = NA,
        ..df2 = NA,
        ..alpha = NA)
)

ftestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ftestResults",
    inherit = jmvcore::Group,
    active = list(
        text2 = function() private$.items[["text2"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Statistical Power for the Generic F Test",
                refs=list(
                    "pwrss"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text2",
                title="One Proportion z test"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="A proportion against a Constant (z Test)",
                renderFun=".plot"))}))

ftestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ftestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jpwrss",
                name = "ftest",
                version = c(1,0,0),
                options = options,
                results = ftestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Statistical Power for the Generic F Test
#'
#' 
#' @param calculate .
#' @param ncp .
#' @param df1 .
#' @param df2 .
#' @param alpha .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text2} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
ftest <- function(
    calculate = "selectpower",
    ncp = 1.96,
    df1 = 2,
    df2 = 199,
    alpha = 0.05) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ftest requires jmvcore to be installed (restart may be required)")


    options <- ftestOptions$new(
        calculate = calculate,
        ncp = ncp,
        df1 = df1,
        df2 = df2,
        alpha = alpha)

    analysis <- ftestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

