
# This file is automatically generated, you probably don't want to edit this

t2meansindepOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "t2meansindepOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            calculate = "selectpower",
            stdinput = FALSE,
            d = 0.2,
            mu1 = 0.2,
            mu2 = 0,
            sd1 = 1,
            sd2 = 1,
            margin = 0,
            power = 0.8,
            alpha = 0.05,
            alternative = "not equal",
            kappa = 1,
            n2 = 200, ...) {

            super$initialize(
                package="jpwrss",
                name="t2meansindep",
                requiresData=FALSE,
                ...)

            private$..calculate <- jmvcore::OptionList$new(
                "calculate",
                calculate,
                options=list(
                    "selectpower",
                    "selectsamplesize"),
                default="selectpower")
            private$..stdinput <- jmvcore::OptionBool$new(
                "stdinput",
                stdinput,
                default=FALSE)
            private$..d <- jmvcore::OptionNumber$new(
                "d",
                d,
                default=0.2)
            private$..mu1 <- jmvcore::OptionNumber$new(
                "mu1",
                mu1,
                default=0.2)
            private$..mu2 <- jmvcore::OptionNumber$new(
                "mu2",
                mu2,
                default=0)
            private$..sd1 <- jmvcore::OptionNumber$new(
                "sd1",
                sd1,
                default=1)
            private$..sd2 <- jmvcore::OptionNumber$new(
                "sd2",
                sd2,
                default=1)
            private$..margin <- jmvcore::OptionNumber$new(
                "margin",
                margin,
                default=0)
            private$..power <- jmvcore::OptionNumber$new(
                "power",
                power,
                default=0.8)
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                default=0.05)
            private$..alternative <- jmvcore::OptionList$new(
                "alternative",
                alternative,
                options=list(
                    "not equal",
                    "greater",
                    "less",
                    "equivalent",
                    "non-inferior",
                    "superior"),
                default="not equal")
            private$..kappa <- jmvcore::OptionNumber$new(
                "kappa",
                kappa,
                default=1)
            private$..n2 <- jmvcore::OptionNumber$new(
                "n2",
                n2,
                default=200)

            self$.addOption(private$..calculate)
            self$.addOption(private$..stdinput)
            self$.addOption(private$..d)
            self$.addOption(private$..mu1)
            self$.addOption(private$..mu2)
            self$.addOption(private$..sd1)
            self$.addOption(private$..sd2)
            self$.addOption(private$..margin)
            self$.addOption(private$..power)
            self$.addOption(private$..alpha)
            self$.addOption(private$..alternative)
            self$.addOption(private$..kappa)
            self$.addOption(private$..n2)
        }),
    active = list(
        calculate = function() private$..calculate$value,
        stdinput = function() private$..stdinput$value,
        d = function() private$..d$value,
        mu1 = function() private$..mu1$value,
        mu2 = function() private$..mu2$value,
        sd1 = function() private$..sd1$value,
        sd2 = function() private$..sd2$value,
        margin = function() private$..margin$value,
        power = function() private$..power$value,
        alpha = function() private$..alpha$value,
        alternative = function() private$..alternative$value,
        kappa = function() private$..kappa$value,
        n2 = function() private$..n2$value),
    private = list(
        ..calculate = NA,
        ..stdinput = NA,
        ..d = NA,
        ..mu1 = NA,
        ..mu2 = NA,
        ..sd1 = NA,
        ..sd2 = NA,
        ..margin = NA,
        ..power = NA,
        ..alpha = NA,
        ..alternative = NA,
        ..kappa = NA,
        ..n2 = NA)
)

t2meansindepResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "t2meansindepResults",
    inherit = jmvcore::Group,
    active = list(
        text2 = function() private$.items[["text2"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Two Independent Means (t Test)",
                refs=list(
                    "pwrss"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text2",
                title="Two Independent Means (t Test)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Two Independent Means (t Test)",
                renderFun=".plot"))}))

t2meansindepBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "t2meansindepBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jpwrss",
                name = "t2meansindep",
                version = c(1,0,0),
                options = options,
                results = t2meansindepResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Two Independent Means (t Test)
#'
#' 
#' @param calculate .
#' @param stdinput .
#' @param d .
#' @param mu1 .
#' @param mu2 .
#' @param sd1 .
#' @param sd2 .
#' @param margin .
#' @param power .
#' @param alpha .
#' @param alternative .
#' @param kappa .
#' @param n2 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text2} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
t2meansindep <- function(
    calculate = "selectpower",
    stdinput = FALSE,
    d = 0.2,
    mu1 = 0.2,
    mu2 = 0,
    sd1 = 1,
    sd2 = 1,
    margin = 0,
    power = 0.8,
    alpha = 0.05,
    alternative = "not equal",
    kappa = 1,
    n2 = 200) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("t2meansindep requires jmvcore to be installed (restart may be required)")


    options <- t2meansindepOptions$new(
        calculate = calculate,
        stdinput = stdinput,
        d = d,
        mu1 = mu1,
        mu2 = mu2,
        sd1 = sd1,
        sd2 = sd2,
        margin = margin,
        power = power,
        alpha = alpha,
        alternative = alternative,
        kappa = kappa,
        n2 = n2)

    analysis <- t2meansindepClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

