
# This file is automatically generated, you probably don't want to edit this

tmeanOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tmeanOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            calculate = "selectpower", 
            mu = 0.20,
            mu0 = 0,
			sd = 1,
            margin = 0,
            power = 0.8,
            alpha = 0.05,
            alternative = "not equal",
            n = 200, ...) {

            super$initialize(
                package="jpwrss",
                name="tmean",
                requiresData=FALSE,
                ...)

            private$..calculate <- jmvcore::OptionList$new(
                "calculate",
                calculate,
                options=list(
                    "selectpower",
                    "selectsamplesize"),
                default="selectpower")

             private$..mu <- jmvcore::OptionNumber$new(
                "mu",
                mu,
                default=0.20)
            private$..mu0 <- jmvcore::OptionNumber$new(
                "mu0",
                mu0,
                default=0)
            private$..margin <- jmvcore::OptionNumber$new(
                "margin",
                margin,
                default=0)
            private$..power <- jmvcore::OptionNumber$new(
                "power",
                power,
                default=0.8)
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                default=0.05)
            private$..alternative <- jmvcore::OptionList$new(
                "alternative",
                alternative,
                options=list(
                    "not equal",
                    "greater",
                    "less",
                    "equivalent",
                    "non-inferior",
                    "superior"),
                default="not equal")
            private$..n <- jmvcore::OptionNumber$new(
                "n",
                n,
                default=200)

            self$.addOption(private$..calculate)
            self$.addOption(private$..mu)
            self$.addOption(private$..mu0)
            self$.addOption(private$..margin)
            self$.addOption(private$..power)
            self$.addOption(private$..alpha)
            self$.addOption(private$..alternative)
            self$.addOption(private$..n)
			
        }),
		
    active = list(
        calculate = function() private$..calculate$value,
        mu = function() private$..mu$value,
        mu0 = function() private$..mu0$value,
        margin = function() private$..margin$value,
        power = function() private$..power$value,
        alpha = function() private$..alpha$value,
        alternative = function() private$..alternative$value,
        n = function() private$..n$value),
    private = list(
        ..calculate = NA,
        ..mu = NA,
        ..mu0 = NA,
        ..margin = NA,
        ..power = NA,
        ..alpha = NA,
        ..alternative = NA,
        ..n = NA)
)

tmeanResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tmeanResults",
    inherit = jmvcore::Group,
    active = list(
        text2 = function() private$.items[["text2"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="One Mean t Test",
                refs=list(
                    "pwrss"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text2",
                title="One Mean t Test"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="One Mean t Test",
                renderFun=".plot"))}))

tmeanBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tmeanBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jpwrss",
                name = "tmean",
                version = c(1,0,0),
                options = options,
                results = tmeanResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' One Mean against a Constant (z or t Test)
#'
#' 
#' @param calculate .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text2} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
tmean <- function(
	calculate = "selectpower",
    mu = 0.20,
    mu0 = 0,
    margin = 0,
    power = 0.8,
    alpha = 0.05,
    alternative = "not equal",
    n = 200) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("tmean requires jmvcore to be installed (restart may be required)")


    options <- tmeanOptions$new(
		calculate = calculate,
        mu = mu,
        mu0 = mu0,
        margin = margin,
        power = power,
        alpha = alpha,
        alternative = alternative,
        n = n)

    analysis <- tmeanClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

