
# This file is automatically generated, you probably don't want to edit this

ttestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ttestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            calculate = "selectpower",
            ncp = 1.96,
            df = 199,
            alpha = 0.05,
            alternative = "not equal", ...) {

            super$initialize(
                package="jpwrss",
                name="ttest",
                requiresData=FALSE,
                ...)

            private$..calculate <- jmvcore::OptionList$new(
                "calculate",
                calculate,
                options=list(
                    "selectpower"),
                default="selectpower")
            private$..ncp <- jmvcore::OptionNumber$new(
                "ncp",
                ncp,
                default=1.96)
            private$..df <- jmvcore::OptionInteger$new(
                "df",
                df,
                default=199)
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                default=0.05)
            private$..alternative <- jmvcore::OptionList$new(
                "alternative",
                alternative,
                options=list(
                    "not equal",
                    "greater",
                    "less"),
                default="not equal")

            self$.addOption(private$..calculate)
            self$.addOption(private$..ncp)
            self$.addOption(private$..df)
            self$.addOption(private$..alpha)
            self$.addOption(private$..alternative)
        }),
    active = list(
        calculate = function() private$..calculate$value,
        ncp = function() private$..ncp$value,
        df = function() private$..df$value,
        alpha = function() private$..alpha$value,
        alternative = function() private$..alternative$value),
    private = list(
        ..calculate = NA,
        ..ncp = NA,
        ..df = NA,
        ..alpha = NA,
        ..alternative = NA)
)

ttestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ttestResults",
    inherit = jmvcore::Group,
    active = list(
        text2 = function() private$.items[["text2"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Statistical Power for the Generic t Test",
                refs=list(
                    "pwrss"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text2",
                title="One Proportion z test"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="A proportion against a Constant (z Test)",
                renderFun=".plot"))}))

ttestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ttestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jpwrss",
                name = "ttest",
                version = c(1,0,0),
                options = options,
                results = ttestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Statistical Power for the Generic t Test
#'
#' 
#' @param calculate .
#' @param ncp .
#' @param df .
#' @param alpha .
#' @param alternative .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text2} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
ttest <- function(
    calculate = "selectpower",
    ncp = 1.96,
    df = 199,
    alpha = 0.05,
    alternative = "not equal") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ttest requires jmvcore to be installed (restart may be required)")


    options <- ttestOptions$new(
        calculate = calculate,
        ncp = ncp,
        df = df,
        alpha = alpha,
        alternative = alternative)

    analysis <- ttestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

