
# This file is automatically generated, you probably don't want to edit this

z2corrsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "z2corrsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            calculate = "selectpower",
            r1 = 0.5,
            r2 = 0.4,
            power = 0.8,
            alpha = 0.05,
            alternative = "not equal",
            kappa = 1,
            n2 = 200, ...) {

            super$initialize(
                package="jpwrss",
                name="z2corrs",
                requiresData=FALSE,
                ...)

            private$..calculate <- jmvcore::OptionList$new(
                "calculate",
                calculate,
                options=list(
                    "selectpower",
                    "selectsamplesize"),
                default="selectpower")
            private$..r1 <- jmvcore::OptionNumber$new(
                "r1",
                r1,
                default=0.5)
            private$..r2 <- jmvcore::OptionNumber$new(
                "r2",
                r2,
                default=0.4)
            private$..power <- jmvcore::OptionNumber$new(
                "power",
                power,
                default=0.8)
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                default=0.05)
            private$..alternative <- jmvcore::OptionList$new(
                "alternative",
                alternative,
                options=list(
                    "not equal",
                    "greater",
                    "less"),
                default="not equal")
            private$..kappa <- jmvcore::OptionNumber$new(
                "kappa",
                kappa,
                default=1)
            private$..n2 <- jmvcore::OptionNumber$new(
                "n2",
                n2,
                default=200)

            self$.addOption(private$..calculate)
            self$.addOption(private$..r1)
            self$.addOption(private$..r2)
            self$.addOption(private$..power)
            self$.addOption(private$..alpha)
            self$.addOption(private$..alternative)
            self$.addOption(private$..kappa)
            self$.addOption(private$..n2)
        }),
    active = list(
        calculate = function() private$..calculate$value,
        r1 = function() private$..r1$value,
        r2 = function() private$..r2$value,
        power = function() private$..power$value,
        alpha = function() private$..alpha$value,
        alternative = function() private$..alternative$value,
        kappa = function() private$..kappa$value,
        n2 = function() private$..n2$value),
    private = list(
        ..calculate = NA,
        ..r1 = NA,
        ..r2 = NA,
        ..power = NA,
        ..alpha = NA,
        ..alternative = NA,
        ..kappa = NA,
        ..n2 = NA)
)

z2corrsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "z2corrsResults",
    inherit = jmvcore::Group,
    active = list(
        text2 = function() private$.items[["text2"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Difference between Two Correlations (Independent Samples z Test)",
                refs=list(
                    "pwrss"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text2",
                title="One Proportion z test"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="A proportion against a Constant (z Test)",
                renderFun=".plot"))}))

z2corrsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "z2corrsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jpwrss",
                name = "z2corrs",
                version = c(1,0,0),
                options = options,
                results = z2corrsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Difference between Two Correlations (Independent Samples z Test)
#'
#' 
#' @param calculate .
#' @param r1 .
#' @param r2 .
#' @param power .
#' @param alpha .
#' @param alternative .
#' @param kappa .
#' @param n2 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text2} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
z2corrs <- function(
    calculate = "selectpower",
    r1 = 0.5,
    r2 = 0.4,
    power = 0.8,
    alpha = 0.05,
    alternative = "not equal",
    kappa = 1,
    n2 = 200) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("z2corrs requires jmvcore to be installed (restart may be required)")


    options <- z2corrsOptions$new(
        calculate = calculate,
        r1 = r1,
        r2 = r2,
        power = power,
        alpha = alpha,
        alternative = alternative,
        kappa = kappa,
        n2 = n2)

    analysis <- z2corrsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

