
# This file is automatically generated, you probably don't want to edit this

z2propsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "z2propsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            calculate = "selectpower",
            p1 = 0.4,
            p2 = 0.5,
            margin = 0,
            power = 0.8,
            alpha = 0.05,
            alternative = "not equal",
            arcsintrans = FALSE,
            kappa = 1,
            n2 = 200, ...) {

            super$initialize(
                package="jpwrss",
                name="z2props",
                requiresData=FALSE,
                ...)

            private$..calculate <- jmvcore::OptionList$new(
                "calculate",
                calculate,
                options=list(
                    "selectpower",
                    "selectsamplesize"),
                default="selectpower")
            private$..p1 <- jmvcore::OptionNumber$new(
                "p1",
                p1,
                default=0.4)
            private$..p2 <- jmvcore::OptionNumber$new(
                "p2",
                p2,
                default=0.5)
            private$..margin <- jmvcore::OptionNumber$new(
                "margin",
                margin,
                default=0)
            private$..power <- jmvcore::OptionNumber$new(
                "power",
                power,
                default=0.8)
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                default=0.05)
            private$..alternative <- jmvcore::OptionList$new(
                "alternative",
                alternative,
                options=list(
                    "not equal",
                    "greater",
                    "less",
                    "equivalent",
                    "non-inferior",
                    "superior"),
                default="not equal")
            private$..arcsintrans <- jmvcore::OptionBool$new(
                "arcsintrans",
                arcsintrans,
                default=FALSE)
            private$..kappa <- jmvcore::OptionNumber$new(
                "kappa",
                kappa,
                default=1)
            private$..n2 <- jmvcore::OptionNumber$new(
                "n2",
                n2,
                default=200)

            self$.addOption(private$..calculate)
            self$.addOption(private$..p1)
            self$.addOption(private$..p2)
            self$.addOption(private$..margin)
            self$.addOption(private$..power)
            self$.addOption(private$..alpha)
            self$.addOption(private$..alternative)
            self$.addOption(private$..arcsintrans)
            self$.addOption(private$..kappa)
            self$.addOption(private$..n2)
        }),
    active = list(
        calculate = function() private$..calculate$value,
        p1 = function() private$..p1$value,
        p2 = function() private$..p2$value,
        margin = function() private$..margin$value,
        power = function() private$..power$value,
        alpha = function() private$..alpha$value,
        alternative = function() private$..alternative$value,
        arcsintrans = function() private$..arcsintrans$value,
        kappa = function() private$..kappa$value,
        n2 = function() private$..n2$value),
    private = list(
        ..calculate = NA,
        ..p1 = NA,
        ..p2 = NA,
        ..margin = NA,
        ..power = NA,
        ..alpha = NA,
        ..alternative = NA,
        ..arcsintrans = NA,
        ..kappa = NA,
        ..n2 = NA)
)

z2propsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "z2propsResults",
    inherit = jmvcore::Group,
    active = list(
        text2 = function() private$.items[["text2"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Two Independent Proportions (z Test)",
                refs=list(
                    "pwrss"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text2",
                title="Two Independent Proportions (z Test)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Two Independent Proportions (z Test)",
                renderFun=".plot"))}))

z2propsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "z2propsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jpwrss",
                name = "z2props",
                version = c(1,0,0),
                options = options,
                results = z2propsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Difference between Two Proportions (z Test)
#'
#' 
#' @param calculate .
#' @param p1 .
#' @param p2 .
#' @param margin .
#' @param power .
#' @param alpha .
#' @param alternative .
#' @param arcsintrans .
#' @param kappa .
#' @param n2 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text2} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
z2props <- function(
    calculate = "selectpower",
    p1 = 0.4,
    p2 = 0.5,
    margin = 0,
    power = 0.8,
    alpha = 0.05,
    alternative = "not equal",
    arcsintrans = FALSE,
    kappa = 1,
    n2 = 200) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("z2props requires jmvcore to be installed (restart may be required)")


    options <- z2propsOptions$new(
        calculate = calculate,
        p1 = p1,
        p2 = p2,
        margin = margin,
        power = power,
        alpha = alpha,
        alternative = alternative,
        arcsintrans = arcsintrans,
        kappa = kappa,
        n2 = n2)

    analysis <- z2propsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

