
# This file is automatically generated, you probably don't want to edit this

z2propsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "z2propsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            calculate = "selectpower", ...) {

            super$initialize(
                package="jpwrss",
                name="z2props",
                requiresData=FALSE,
                ...)

            private$..calculate <- jmvcore::OptionList$new(
                "calculate",
                calculate,
                options=list(
                    "selectpower",
                    "selectsamplesize"),
                default="selectpower")

            self$.addOption(private$..calculate)
        }),
    active = list(
        calculate = function() private$..calculate$value),
    private = list(
        ..calculate = NA)
)

z2propsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "z2propsResults",
    inherit = jmvcore::Group,
    active = list(
        text2 = function() private$.items[["text2"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Difference between Two Proportions (z Test)",
                refs=list(
                    "pwrss"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text2",
                title="One Proportion z test"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="A proportion against a Constant (z Test)",
                renderFun=".plot"))}))

z2propsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "z2propsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jpwrss",
                name = "z2props",
                version = c(1,0,0),
                options = options,
                results = z2propsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Difference between Two Proportions (z Test)
#'
#' 
#' @param calculate .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text2} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
z2props <- function(
    calculate = "selectpower") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("z2props requires jmvcore to be installed (restart may be required)")


    options <- z2propsOptions$new(
        calculate = calculate)

    analysis <- z2propsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

