
# This file is automatically generated, you probably don't want to edit this

zmedOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "zmedOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            calculate = "selectpower",
            predictor = "continuous",
            stdinput = FALSE,
            p = 0.5,
            a = 0.25,
            b = 0,
            cp = 0,
            sdy = 1,
            sdx = 1,
            sdm = 1,
            r2y = 0,
            power = 0.8,
            alpha = 0.05,
            alternative = "not equal",
            n = 200, ...) {

            super$initialize(
                package="jpwrss",
                name="zmed",
                requiresData=FALSE,
                ...)

            private$..calculate <- jmvcore::OptionList$new(
                "calculate",
                calculate,
                options=list(
                    "selectpower",
                    "selectsamplesize"),
                default="selectpower")
            private$..predictor <- jmvcore::OptionList$new(
                "predictor",
                predictor,
                options=list(
                    "binary",
                    "continuous"),
                default="continuous")
            private$..stdinput <- jmvcore::OptionBool$new(
                "stdinput",
                stdinput,
                default=FALSE)
            private$..p <- jmvcore::OptionNumber$new(
                "p",
                p,
                default=0.5)
            private$..a <- jmvcore::OptionNumber$new(
                "a",
                a,
                default=0.25)
            private$..b <- jmvcore::OptionNumber$new(
                "b",
                b,
                default=0)
            private$..cp <- jmvcore::OptionNumber$new(
                "cp",
                cp,
                default=0)
            private$..sdy <- jmvcore::OptionNumber$new(
                "sdy",
                sdy,
                default=1)
            private$..sdx <- jmvcore::OptionNumber$new(
                "sdx",
                sdx,
                default=1)
            private$..sdm <- jmvcore::OptionNumber$new(
                "sdm",
                sdm,
                default=1)
            private$..r2y <- jmvcore::OptionNumber$new(
                "r2y",
                r2y,
                default=0)
            private$..power <- jmvcore::OptionNumber$new(
                "power",
                power,
                default=0.8)
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                default=0.05)
            private$..alternative <- jmvcore::OptionList$new(
                "alternative",
                alternative,
                options=list(
                    "not equal",
                    "greater",
                    "less"),
                default="not equal")
            private$..n <- jmvcore::OptionNumber$new(
                "n",
                n,
                default=200)

            self$.addOption(private$..calculate)
            self$.addOption(private$..predictor)
            self$.addOption(private$..stdinput)
            self$.addOption(private$..p)
            self$.addOption(private$..a)
            self$.addOption(private$..b)
            self$.addOption(private$..cp)
            self$.addOption(private$..sdy)
            self$.addOption(private$..sdx)
            self$.addOption(private$..sdm)
            self$.addOption(private$..r2y)
            self$.addOption(private$..power)
            self$.addOption(private$..alpha)
            self$.addOption(private$..alternative)
            self$.addOption(private$..n)
        }),
    active = list(
        calculate = function() private$..calculate$value,
        predictor = function() private$..predictor$value,
        stdinput = function() private$..stdinput$value,
        p = function() private$..p$value,
        a = function() private$..a$value,
        b = function() private$..b$value,
        cp = function() private$..cp$value,
        sdy = function() private$..sdy$value,
        sdx = function() private$..sdx$value,
        sdm = function() private$..sdm$value,
        r2y = function() private$..r2y$value,
        power = function() private$..power$value,
        alpha = function() private$..alpha$value,
        alternative = function() private$..alternative$value,
        n = function() private$..n$value),
    private = list(
        ..calculate = NA,
        ..predictor = NA,
        ..stdinput = NA,
        ..p = NA,
        ..a = NA,
        ..b = NA,
        ..cp = NA,
        ..sdy = NA,
        ..sdx = NA,
        ..sdm = NA,
        ..r2y = NA,
        ..power = NA,
        ..alpha = NA,
        ..alternative = NA,
        ..n = NA)
)

zmedResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "zmedResults",
    inherit = jmvcore::Group,
    active = list(
        text2 = function() private$.items[["text2"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Mediation (Sobel's z Test)",
                refs=list(
                    "pwrss"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text2",
                title="Mediation (Sobel's z Test)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Mediation (Sobel's z Test)",
                renderFun=".plot"))}))

zmedBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "zmedBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jpwrss",
                name = "zmed",
                version = c(1,0,0),
                options = options,
                results = zmedResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Mediation (Sobel's z Test)
#'
#' 
#' @param calculate .
#' @param predictor .
#' @param stdinput .
#' @param p .
#' @param a .
#' @param b .
#' @param cp .
#' @param sdy .
#' @param sdx .
#' @param sdm .
#' @param r2y .
#' @param power .
#' @param alpha .
#' @param alternative .
#' @param n .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text2} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
zmed <- function(
    calculate = "selectpower",
    predictor = "continuous",
    stdinput = FALSE,
    p = 0.5,
    a = 0.25,
    b = 0,
    cp = 0,
    sdy = 1,
    sdx = 1,
    sdm = 1,
    r2y = 0,
    power = 0.8,
    alpha = 0.05,
    alternative = "not equal",
    n = 200) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("zmed requires jmvcore to be installed (restart may be required)")


    options <- zmedOptions$new(
        calculate = calculate,
        predictor = predictor,
        stdinput = stdinput,
        p = p,
        a = a,
        b = b,
        cp = cp,
        sdy = sdy,
        sdx = sdx,
        sdm = sdm,
        r2y = r2y,
        power = power,
        alpha = alpha,
        alternative = alternative,
        n = n)

    analysis <- zmedClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

