
# This file is automatically generated, you probably don't want to edit this

zpropOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "zpropOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            calculate = "selectpower",
            p = 0.4,
            p0 = 0.5, ...) {

            super$initialize(
                package="jpwrss",
                name="zprop",
                requiresData=FALSE,
                ...)

            private$..calculate <- jmvcore::OptionList$new(
                "calculate",
                calculate,
                options=list(
                    "selectpower",
                    "selectsamplesize"),
                default="selectpower")
            private$..p <- jmvcore::OptionNumber$new(
                "p",
                p,
                default=0.4)
            private$..p0 <- jmvcore::OptionNumber$new(
                "p0",
                p0,
                default=0.5)

            self$.addOption(private$..calculate)
            self$.addOption(private$..p)
            self$.addOption(private$..p0)
        }),
    active = list(
        calculate = function() private$..calculate$value,
        p = function() private$..p$value,
        p0 = function() private$..p0$value),
    private = list(
        ..calculate = NA,
        ..p = NA,
        ..p0 = NA)
)

zpropResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "zpropResults",
    inherit = jmvcore::Group,
    active = list(
        text1 = function() private$.items[["text1"]],
        text2 = function() private$.items[["text2"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="One Proportion z test",
                refs=list(
                    "pwrss"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text1",
                title="One Proportion z test"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text2",
                title="One Proportion z test"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="A proportion against a Constant (z Test)",
                renderFun=".plot"))}))

zpropBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "zpropBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jpwrss",
                name = "zprop",
                version = c(1,0,0),
                options = options,
                results = zpropResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' One Proportion z test
#'
#' 
#' @param calculate .
#' @param p .
#' @param p0 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text1} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$text2} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
zprop <- function(
    calculate = "selectpower",
    p = 0.4,
    p0 = 0.5) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("zprop requires jmvcore to be installed (restart may be required)")


    options <- zpropOptions$new(
        calculate = calculate,
        p = p,
        p0 = p0)

    analysis <- zpropClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

