
# This file is automatically generated, you probably don't want to edit this

ztestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ztestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            calculate = "selectpower",
            ncp = 1.96,
            alpha = 0.05,
            alternative = "not equal", ...) {

            super$initialize(
                package="jpwrss",
                name="ztest",
                requiresData=FALSE,
                ...)

            private$..calculate <- jmvcore::OptionList$new(
                "calculate",
                calculate,
                options=list(
                    "selectpower"),
                default="selectpower")
            private$..ncp <- jmvcore::OptionNumber$new(
                "ncp",
                ncp,
                default=1.96)
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                default=0.05)
            private$..alternative <- jmvcore::OptionList$new(
                "alternative",
                alternative,
                options=list(
                    "not equal",
                    "greater",
                    "less"),
                default="not equal")

            self$.addOption(private$..calculate)
            self$.addOption(private$..ncp)
            self$.addOption(private$..alpha)
            self$.addOption(private$..alternative)
        }),
    active = list(
        calculate = function() private$..calculate$value,
        ncp = function() private$..ncp$value,
        alpha = function() private$..alpha$value,
        alternative = function() private$..alternative$value),
    private = list(
        ..calculate = NA,
        ..ncp = NA,
        ..alpha = NA,
        ..alternative = NA)
)

ztestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ztestResults",
    inherit = jmvcore::Group,
    active = list(
        text2 = function() private$.items[["text2"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Statistical Power for the Generic z Test",
                refs=list(
                    "pwrss"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text2",
                title="One Proportion z test"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="A proportion against a Constant (z Test)",
                renderFun=".plot"))}))

ztestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ztestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jpwrss",
                name = "ztest",
                version = c(1,0,0),
                options = options,
                results = ztestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Statistical Power for the Generic z Test
#'
#' 
#' @param calculate .
#' @param ncp .
#' @param alpha .
#' @param alternative .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text2} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
ztest <- function(
    calculate = "selectpower",
    ncp = 1.96,
    alpha = 0.05,
    alternative = "not equal") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ztest requires jmvcore to be installed (restart may be required)")


    options <- ztestOptions$new(
        calculate = calculate,
        ncp = ncp,
        alpha = alpha,
        alternative = alternative)

    analysis <- ztestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

